apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: simple-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: api_service:latest
        imagePullPolicy: Never
        env:
        - name: DB_SERVICE_URL
          value: http://db-service:8000
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: simple-app 
spec:
  selector:
    app: api-service
  type: LoadBalancer  # This makes the service accessible from outside the cluster
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000