apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-service
  namespace: simple-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-service
  template:
    metadata:
      labels:
        app: api-service
    spec:
      containers:
      - name: api-service
        image: ludomitch/api-service:latest
        env:
        - name: DB_SERVICE_URL
          value: http://db-service:8000
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: simple-app
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "false"
spec:
  selector:
    app: api-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30010
