apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
      - name: db-service
        image: db_service:latest
        imagePullPolicy: Never
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: mydb
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: password
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  selector:
    app: db-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000