
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-service
  namespace: simple-app 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
      - name: db-service
        image: ludomitch/db-service:latest
        env:
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: mydb
        - name: DB_USER
          value: user
        - name: DB_PASSWORD
          value: password
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: simple-app 
spec:
  selector:
    app: db-service
  type: ClusterIP  # Change to ClusterIP as it doesn't need external access
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
